#!/bin/bash

export HDFS_NAMENODE_HOSTNAME=${HDFS_NAMENODE_HOSTNAME=hadoop-namenode}
export HDFS_DATANODE_DIRS=${HDFS_DATANODE_DIRS=/mnt/dataNode1,/mnt/dataNode2}
export HDFS_NAMENODE_DIRS=${HDFS_NAMENODE_DIRS=/mnt/nameNode1,/mnt/nameNode2}
export HDFS_REPLICATION_FACTOR=${HDFS_REPLICATION_FACTOR=2}

export YARN_RESOURCEMANAGER_HOSTNAME=${YARN_RESOURCEMANAGER_HOSTNAME=hadoop-resourcemanager}
export YARN_NODEMANAGER_LOCALDIRS=${YARN_NODEMANAGER_LOCALDIRS=/mnt/nodeManager1/intermediate,/mnt/nodeManager2/intermediate}
export YARN_NODEMANAGER_LOGDIRS=${YARN_NODEMANAGER_LOGDIRS=/mnt/nodeManager1/logs,/mnt/nodeManager2/logs}
export YARN_NODEMANAGER_CORES=${YARN_NODEMANAGER_CORES=32}
export YARN_NODEMANAGER_MEMORY=${YARN_NODEMANAGER_MEMORY=65536}
export YARN_NODEMANAGER_PMEM_CHECK_ENABLED=${YARN_NODEMANAGER_PMEM_CHECK_ENABLED=true}
export YARN_NODEMANAGER_VMEM_CHECK_ENABLED=${YARN_NODEMANAGER_VMEM_CHECK_ENABLED=true}
export YARN_NODEMANAGER_VMEM_PMEM_RATIO=${YARN_NODEMANAGER_VMEM_PMEM_RATIO=2.1}
export YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB=${YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB=131072}

export MAPREDUCE_HISTORYSERVER_HOSTNAME=${MAPREDUCE_HISTORYSERVER_HOSTNAME=hadoop-historyserver}

